sudo: false
dist: xenial
language: python
matrix:
  include:
    - name: py27-pylint27
      python: 2.7
      env: TOXENV=py27,pylint27
    - name: py36
      python: 3.6
      env: TOXENV=py36
    - name: py37-pylint37-docs-doctest
      python: 3.7
      env: TOXENV=py37,pylint37,docs,doctest
    - name: docker-robottests
      python: 3.7
      env: TOXENV=docker-robottests
install:
  - pip install tox
script: tox
