#!/bin/bash
SCRIPT_DIR="$(dirname $(readlink -f ${BASH_SOURCE[0]}))"
docker build --rm -t test .
docker run \
--add-host=python2host:127.0.0.1 \
--add-host=python3host:127.0.0.1 \
-v ${SCRIPT_DIR}/..:/work \
--rm test
